config/routes.rb
Collaboration::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "home#index"
  get "home/index"

  resources :orgs do
    resources :projects do
      resources :acls
    end
    resources :groups do
      resources :group_members, :path => 'members', :only => [:new, :create, :destroy, :index]
    end
    resources :owned_resources
  end

  resources :apps do
    member do
      get 'visit'
    end
    collection do
      get 'import'
    end
  end
  resources :services do
    collection do
      get 'import'
    end
  end
  resources :users do
    resources :email_addresses, :only => [:index], :controller => "users/email_addresses"
    resources :access_tokens, :controller => "users/access_tokens"
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :org
  has_many :acls, :as => :entity
  has_many :projects, :through => :acls
  has_many :group_members, :dependent => :destroy

  validates_uniqueness_of :display_name, :scope => :org_id
  validates_presence_of :display_name

  public
    def includes? user
      group_members.each do |member|
        return true if (member.user_id == user.id)
      end
      false
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :identify_parent

  # GET /groups
  # GET /groups.json
  def index
    @groups = @org.groups

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = @org.groups.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = @org.groups.build

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = @org.groups.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = @org.groups.build(params[:group])

    respond_to do |format|
      if @group.save
        flash[:notice] = 'Group was successfully created.'
        format.html { redirect_to org_group_path(@org, @group) }
        format.json  { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = @org.groups.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:notice] = 'Group was successfully updated.'
        format.html { redirect_to org_group_path(@org, @group) }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = @org.groups.find(params[:id])
    @group.destroy

    respond_to do |format|
      flash[:notice] = 'Group was successfully deleted.'
      format.html { redirect_to(org_groups_url(@org)) }
      format.json  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div data-role="content">
  <%= form_for([@org, @group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation" data-role="content" data-theme='e'>
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/groups/edit.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', org_groups_path(@org), :class => "ui-btn-left" %>
  <h1>Editing group</h1>
  <%= link_to 'Destroy', org_group_path(@org, @group), :confirm => 'Are you sure?', :method => :delete, :class => "ui-btn-right" %>
<%- end %>
<%= render 'form' %>

app/views/groups/index.html.erb
<%- content_for :header do %>
 <%= link_to "Back", @org, :class => "ui-btn-left" %>
 <h1>Groups</h1>
  <%=link_to 'New Group', new_org_group_path(@org), :class => 'ui-btn-right', "data-icon" => "plus" %>
<%- end %>

<div data-role="content">
  <ul data-role="listview" data-inset="true">
    <% @groups.each do |group| %>
        <li><%= link_to group.display_name, org_group_path(@org, group) %></li>
    <%-end%>
</ul>
</div>

app/views/groups/new.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', org_groups_path(@org), :class => "ui-btn-left" %>
  <h1>New group</h1>

<%- end %>
<%= render 'form' %>

app/views/groups/show.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', org_groups_path(@org), :class => "ui-btn-left" %>
  <h1><%= @group.display_name %></h1>
  <%= link_to 'Edit', edit_org_group_path(@org, @group), :class => "ui-btn-right" %>
<%- end %>


<%= link_to 'View Members', org_group_group_members_path(@org, @group), 'data-role'=>"button", 'data-inline'=>"true"  %>