config/routes.rb
Collaboration::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "home#index"
  get "home/index"

  resources :orgs do
    resources :projects do
      resources :acls
    end
    resources :groups do
      resources :group_members, :path => 'members', :only => [:new, :create, :destroy, :index]
    end
    resources :owned_resources
  end

  resources :apps do
    member do
      get 'visit'
    end
    collection do
      get 'import'
    end
  end
  resources :services do
    collection do
      get 'import'
    end
  end
  resources :users do
    resources :email_addresses, :only => [:index], :controller => "users/email_addresses"
    resources :access_tokens, :controller => "users/access_tokens"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :email_addresses, :dependent => :destroy
  has_many :acls, :as => :entity
  has_many :projects, :through => :acls

  has_many :group_members, :dependent => :destroy
  has_many :groups, :through => :group_members

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def emails
    email_addresses.collect(&:email).join(', ')
  end

  def emails=value
    if (value != self.emails)
      email_addys = value.split(',')
      email_addys.each do |email|
        email = email.strip
        unless emails.include? email
          email_addresses.build :email => email
          # TODO not validated
        end
      end
    end
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :emails, :avatar, :remote_avatar_url, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :display_name, :username, :personal_org, :orgs_with_access

  attr_readonly :personal_org

  validates_presence_of :display_name

  mount_uploader :avatar, AvatarUploader

  before_create do
    self.email_addresses.build :email => email
  end

  after_create do
    Org.create! :creator => self, :display_name => "#{display_name}'s Personal Org", :personal => true
  end

  class << self
    def new_with_session(params, session)
      super.tap do |user|
        if session['devise.omniauth_info']
          if data = session['devise.omniauth_info']['user_info']
            user.display_name = data['name'] if data.has_key? 'name'
            user.email = data['email']
            user.username = data['nickname'] if data.has_key? 'nickname'
            user.first_name = data['first_name'] if data.has_key? 'first_name'
            user.last_name = data['last_name'] if data.has_key? 'last_name'
            if data.has_key? 'image'
              user.remote_avatar_url = data['image']
              user.remote_avatar_url.gsub! "square", "large"
            end
            user.password = Devise.friendly_token[0,20]
            user.password_confirmation = user.password
          end
        end
      end
    end
  end

  def set_token_from_hash(hash)
    token = self.authorizations.find_or_initialize_by_provider(hash[:provider])
    token.update_attributes(
      :uid         => hash[:uid],
      :nickname    => hash[:nickname],
      :url         => hash[:url],
      :credentials => hash[:credentials]
    )
  end

public
  def to_s
    display_name
  end

  def includes? user
    return user == self
  end

  def external_identities
    identities = UserAccessToken.get_tokens(self).collect &:provider
    identities.uniq
  end

  def self.get_user_from_auth_by_email(email, signed_in_resource=nil)
    if addy = EmailAddress.find_by_email(email)
      addy.user
    elsif user = User.find_by_email(email)
      logger.debug "Cleaning user record #{email}"
      user.email_addresses.build :email => email, :validated => true
      user.save!
      return user
    elsif (signed_in_resource.nil?)
      User.create(:email => email, :password => Devise.friendly_token[0,20])
    else
      # Facebook and Cloud Foundry only provide validated email addresses
      signed_in_resource.email_addresses.build :email => email, :validated => true
      signed_in_resource.save!
      signed_in_resource
    end
  end

  def self.get_user_from_auth_by_id(provider, id, signed_in_resource=nil)
    rec = UserAccessToken.get_user_by_provider_and_id provider, id
    if rec
      begin
        return User.find rec.user_id
      rescue
        logger.info "Cleaning orphan User Access Token record #{rec}"
        rec.delete
      end
    end
    signed_in_resource
  end


  def orgs_with_access
    orgs = []
    groups.each do |group|
      group.projects.each do |project|
        orgs << project.org
      end
    end
    projects.each do |project|
      orgs << project.org
    end
    orgs.uniq
  end

  def personal_org
    groups.each do |group|
      if group.display_name == 'Admins'
        if group.org.personal?
          return group.org
        end
      end
    end
    return nil
  end

end

app/controllers/users/access_tokens_controller.rb
class Users::AccessTokensController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tokens = UserAccessToken.access_tokens_for_user @user.id

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @tokens }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @token = UserAccessToken.find(params[:id])
    if (@token.user_id == @user.id)
      @token.destroy
    end

    respond_to do |format|
      format.html { redirect_to(user_access_tokens_url(@user)) }
      format.json  { head :ok }
    end
  end

end

app/controllers/users/email_addresses_controller.rb
class Users::EmailAddressesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @emails = @user.email_addresses

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @emails }
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    handle_oauth :facebook
  end

  def cloudfoundry
    handle_oauth :cloudfoundry
  end

  def github
    handle_oauth :github
  end


  def handle_oauth provider
    if (env && env["omniauth.auth"] && env["omniauth.auth"]['credentials'])
       # Get email from external service the current user just authenticated with
      id = env["omniauth.auth"]['uid']

      @user = nil
      if (env["omniauth.auth"]['user_info']['email'])
        email = env["omniauth.auth"]['user_info']['email']
        id = email
        # Find a user with that email or return the current user
        @user = User.get_user_from_auth_by_email email, current_user
      end

      unless @user
        @user = User.get_user_from_auth_by_id provider, id, current_user
      end

      # Store the Access token under the email address or unique id
      ut = UserAccessToken.add_tokens email, id, provider, env["omniauth.auth"]['credentials']

      if @user && @user.persisted?
        # If the user already existed
        # Make sure the access token is pointing to the proper user
        ut.update_attribute :user_id, @user.id

        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => provider

        if (current_user != @user)
          flash[:notice] = "Switching logged in user to #{@user.display_name}"
        end
        sign_in_and_redirect @user, :event => :authentication
      else
        flash[:notice] = 'Please complete registration to App Gallery'

        # Persist the data
        session["devise.omniauth_info"] = env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    else
      flash[:notice] = 'Not enough information to sign in'
      redirect_to new_user_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.json  { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div data-role="content">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" data-role="content" data-theme='e'>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label 'Avatar' %> <br />
    <%= f.text_field :remote_avatar_url %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :emails %><br />
    <%= f.text_field :emails %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', users_path, :class => "ui-btn-left"  %>
  <h1>Editing user</h1>
  <%= link_to 'Destroy User', user_path(@user), :confirm => 'Are you sure?', 'data-role'=>"button", 'data-inline'=>"true", :method => :delete, 'data-icon'=>"delete"%>
<%- end %>

<%= render 'form' %>

app/views/users/index.html.erb
<%- content_for :header do %>
  <%= link_to 'Home', home_index_path, :class => 'ui-btn-left', "data-icon" => "home" %>
  <h1>Listing users</h1>
<%- end %>

<div data-role="content">
<ul data-role="listview" data-inset="true">
<% @users.each do |user| %>
  <li><a href='<%=user_path(user)%>'><img src='<%= user.avatar.url %>'/><h3><%= user.display_name  %></h3></a> </li>
<% end %>
</ul>
</div>

app/views/users/new.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', users_path %>
  <h1>New user</h1>
<%- end %>

<%= render 'form' %>

app/views/users/show.html.erb
<%- content_for :header do %>
<%= link_to 'Back', users_path, :class => 'ui-btn-left' %>
<h1><%= @user.display_name %></h1>
<%= link_to 'Edit', edit_user_path(@user),:class => 'ui-btn-right' %>
<%- end %>

<div data-role="content">
  <img src='<%= @user.avatar.url %>' style='width:100px' />
  <h3><%= @user.display_name %></h3>
    <ul data-role="listview">
        <li><label>First name</label>: <%= @user.first_name %></li>
        <li><label>Last name</label>: <%= @user.last_name %></li>
        <li><label>Username</label>: <%= @user.username %></li>
      <li><%= link_to 'Emails', user_email_addresses_path(@user) %></li>
      <li><%= link_to 'Access Tokens', user_access_tokens_path(@user) %></li>
     </ul>
</div>