config/routes.rb
Collaboration::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "home#index"
  get "home/index"

  resources :orgs do
    resources :projects do
      resources :acls
    end
    resources :groups do
      resources :group_members, :path => 'members', :only => [:new, :create, :destroy, :index]
    end
    resources :owned_resources
  end

  resources :apps do
    member do
      get 'visit'
    end
    collection do
      get 'import'
    end
  end
  resources :services do
    collection do
      get 'import'
    end
  end
  resources :users do
    resources :email_addresses, :only => [:index], :controller => "users/email_addresses"
    resources :access_tokens, :controller => "users/access_tokens"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session.has_key? :url_after_oauth
      redirect_to session[:url_after_oauth]
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%- content_for :header do %>
    <h1>App Gallery</h1>
<% end -%>
<div data-role="content">
  <div class="home">
    <div class="homebox">
      <div class="homebuddy">
        <a href="<%= user_path(current_user) %>"><img src="<%= current_user.avatar_url %>"/></a>
        <h3>Welcome <%= link_to current_user.first_name, user_path(current_user) %></h3>
      </div>
      <br/>
      <p>&nbsp;</p>
      <div class="homep">
        In this gallery you will be able to showcase your code and collaborate with other developers.
        We put special attention to highlight your skills in different services and in
        different frameworks.
      </div>
    </div>
    <div class="homebox">
      <h3>To get started</h3>
        <ol>
          <li>Add or import your <%= link_to 'Cloud Foundry Apps', apps_path %></li>
          <li>Link them to your <%= link_to 'GitHub', 'http://github.com', 'rel' =>'external' %> Repos</li>
          <li>Link them to your <%=link_to 'Facebook Apps', 'https://developers.facebook.com/apps', 'rel' => 'external' %></li>
          <li>Write some new features</li>
          <li>Share with your friends and followers</li>
          <li>Respond to feedback and repeat</li>
        </ol>
    </div>
    <div class="homebox">
      <h3>Security</h3>
      <p>By default when you created your account you were given
        a <%= link_to 'Personal Organization', current_user.personal_org ? org_path(current_user.personal_org) : '' %>.
        Note that you can always create more <%= link_to 'organizations', orgs_path %> to manage permissions, as well
        as be invited by someone else to be part of an organization.</p>
    </div>
  </div>
</div>