config/routes.rb
Collaboration::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "home#index"
  get "home/index"

  resources :orgs do
    resources :projects do
      resources :acls
    end
    resources :groups do
      resources :group_members, :path => 'members', :only => [:new, :create, :destroy, :index]
    end
    resources :owned_resources
  end

  resources :apps do
    member do
      get 'visit'
    end
    collection do
      get 'import'
    end
  end
  resources :services do
    collection do
      get 'import'
    end
  end
  resources :users do
    resources :email_addresses, :only => [:index], :controller => "users/email_addresses"
    resources :access_tokens, :controller => "users/access_tokens"
  end

end

app/views/apps/_form.html.erb
<div data-role="content">
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation" data-role="content" data-theme='e'>
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><strong><%= msg %></strong></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" data-role="fieldcontain">
    <%= f.label :url %><%= f.text_field :url %>

    <%- if @app.id %>
    <div class="fb-like" data-href='<%= "http://#{@app.url}" %>' data-send="true" data-width="350" data-show-faces="false"></div>
    <%= link_to 'Visit', visit_app_path(@app), :target=>'_blank', :rel => 'external', 'data-role'=>'button', 'data-inline' => 'true' %>
    <%-end%>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :display_name %><%= f.text_field :display_name %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :description %><%= f.text_field :description %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :framework %><%= f.text_field :framework %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :runtime %><%= f.text_field :runtime %>
  </div>

   <%- if @app.id %>
     <div class="field" data-role="fieldcontain">
        <%= f.label :owner %>
        <%= link_to @app.main_owned_resource.owner.display_name, org_path(@app.main_owned_resource.owner), 'data-role'=>"button", 'data-inline'=>"true" %>
        </div>
  <%- end %>

  <%-if @projects %>
      <div class="field" data-role="fieldcontain">
       <%= f.label :project_id %><%= f.select :project_id, @projects %>
      </div>
  <%- end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 </div>

app/views/apps/edit.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', apps_path, :class => "ui-btn-left" %>
  <h1>Editing app</h1>
  <%= link_to 'Destroy App', app_path(@app), :confirm => 'Are you sure?', 'data-role'=>"button", 'data-inline'=>"true", :method => :delete, 'data-icon'=>"delete"%>
<%- end %>

<%= render 'form' %>

  <%- if @app.state == "STOPPED" %>
  <%= link_to 'Start', app_path(@app), 'data-role'=>"button", 'data-inline'=>"true" %>
  <%- else %>
  <%= link_to 'Stop', app_path(@app), 'data-role'=>"button", 'data-inline'=>"true" %>
  <%- end %>

app/views/apps/index.html.erb
<%- content_for :header do %>
  <%= link_to 'Import', import_apps_path, :class => 'ui-btn-left', "data-icon" => "gear", :rel => 'external' %>
  <h1>Applications</h1>
  <%= link_to 'New App', new_app_path, :class => 'ui-btn-right', "data-icon" => "plus" %>
<%- end %>


<div data-role="content">
<%-if @apps.count > 0 %>
<p>This is the current list of applications that you can access:</p>
<ul data-role="listview" data-inset="true">
<% @apps.each do |app| %>
  <li>
    <a href="<%= edit_app_path(app) %>">
    <h3><%= app.display_name %></h3>
    <p><%= app.state %></p>
    <p><%= (app.latest_health_snapshot) ? app.latest_health_snapshot.percentage : '?' %> % running</p>
    </a>
    <%= link_to 'Visit', visit_app_path(app), :target=>'_blank', :rel => 'external', 'data-role'=>'button', 'data-inline' => 'true' %>
  </li>
<% end %>
</ul>
<%- else %>
<p>You do not have any applications. Get started by creating a <%= link_to 'New App', new_app_path %></p>
<%- end %>
</div>

app/views/apps/new.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', apps_path, :class => "ui-btn-left" %>
  <h1>New app</h1>
<%- end %>

<%= render 'form' %>

app/views/apps/show.html.erb
<%- content_for :header do %>
  <%= link_to 'Back', apps_path, :class => 'ui-btn-left' %>
  <h1><%= link_to @app.display_name, @app.url, :target=> '_blank', :style => "text-decoration:none; color:white" %></h1>
  <%= link_to 'Edit', edit_app_path(@app), :class => 'ui-btn-right'%>
<%- end %>

<div data-role="content">
<%= form_for(@app) do |f| %>
 <div class="field" data-role="fieldcontain">
    <%= f.label :display_name %><%= f.text_field :display_name, :readonly=>true %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :description %><%= f.text_area :description, :readonly=>true %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :url %><%= f.text_field :url, :readonly=>true %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :framework %><%= f.text_field :framework, :readonly=>true %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :runtime %><%= f.text_field :runtime, :readonly=>true %>
  </div>
<%- end %>
</div>